"""Emit every number the manuscript's dataset description prints, from the panel.

Run:  PYTHONPATH=scripts uv run --no-project --with numpy --python 3.12 \
          python scripts/generate_panel_description.py

D3 and D9 in docs/OPEN_DEFECTS.md are the same defect twice: panel statistics and
a class breakdown carried by hand from the 12-family pilot into a manuscript
describing the expanded panel, and left there through the Rfam expansion, the
duplicate-annotation correction and the annotation repair. Correcting the numbers
by hand would reproduce the defect at the next correction, so this script writes
them and paper/generated/panel_description.tex is what the manuscript includes.

The panel is the set of records `load_rfam_families` loads: 52 curated, minus the
records withdrawn by repair_annotations.py, which carry an `excluded` block.

No model is run.
"""

import json
import statistics
from pathlib import Path

from audit_panel_classes import classify

REPO = Path(__file__).resolve().parents[1]
FAMILIES = REPO / "data/rfam_families"
OUT = REPO / "paper/generated/panel_description.tex"
TABLE = REPO / "paper/generated/panel_table.tex"
MANIFEST = REPO / "docs/annotation_repair_manifest.json"

# repair_annotations.py's disposition, as the supplement reports it.
DISPOSITION = {"ADOPT STRUCTURE": "structure repaired", "ADOPT MEMBER": "record repaired",
               "DROP": "withdrawn", "DEFER": "withdrawn", "NO REPAIR": ""}


def panel() -> tuple[list[dict], list[dict]]:
    """(analyzed, withdrawn) -- every curated record, split by the exclusion block."""
    records = [json.loads(p.read_text()) for p in sorted(FAMILIES.glob("*.json"))]
    return ([r for r in records if "excluded" not in r],
            [r for r in records if "excluded" in r])


def gc(record: dict) -> tuple[float, float] | None:
    """(stem GC%, loop GC%), or None when the annotation has no stem or no loop."""
    sequence, brackets = record["sequence"].upper(), record["dot_bracket"]
    stem = [i for i, c in enumerate(brackets) if c in "()"]
    loop = [i for i, c in enumerate(brackets) if c == "."]
    if not stem or not loop:
        return None
    return (sum(sequence[i] in "GC" for i in stem) / len(stem) * 100,
            sum(sequence[i] in "GC" for i in loop) / len(loop) * 100)


def accession(record: dict) -> str:
    """The seed member a record names, or an em dash when it names none."""
    source = record.get("source") or ""
    marker = "seed alignment member ("
    return source[source.index(marker) + len(marker):-1] if marker in source else "---"


def tex(text: str) -> str:
    """Escape the characters a family name, accession or reason can carry."""
    for char in ("\\", "_", "%", "&", "#", "$"):
        text = text.replace(char, "\\" + char)
    return text


def panel_table(analyzed: list[dict], withdrawn: list[dict]) -> str:
    disposition = {d["name"]: DISPOSITION[d["disposition"]]
                   for d in json.loads(MANIFEST.read_text())["decisions"]}
    rows = []
    for record in sorted(analyzed, key=lambda r: r["name"]) + \
            sorted(withdrawn, key=lambda r: r["name"]):
        note = disposition.get(record["name"], "")
        if "excluded" in record:
            note = f"withdrawn: {record['excluded']['reason']}"
        rows.append(" & ".join([
            tex(record["name"]),
            classify(record["name"]),
            record.get("rfam_id") or "---",
            tex(accession(record)),
            str(record["length"]),
            tex(note)]) + r" \\")
    return "\n".join([
        r"% Generated by scripts/generate_panel_description.py. Do not edit.",
        r"\begin{longtable}{llllrp{0.28\textwidth}}",
        r"\caption{The curated panel. Families above the rule are analyzed; those "
        r"below carry an annotation that could not be repaired against the Rfam "
        r"seed alignment and are withdrawn. Accession names the seed member a "
        r"record's sequence and structure come from.}"
        r"\label{tab:panel}\\",
        r"\toprule",
        r"\textbf{Family} & \textbf{Class} & \textbf{Rfam} & "
        r"\textbf{Accession} & \textbf{nt} & \textbf{Note} \\",
        r"\midrule\endfirsthead",
        r"\toprule",
        r"\textbf{Family} & \textbf{Class} & \textbf{Rfam} & "
        r"\textbf{Accession} & \textbf{nt} & \textbf{Note} \\",
        r"\midrule\endhead",
        *rows[:len(analyzed)],
        r"\midrule",
        *rows[len(analyzed):],
        r"\bottomrule",
        r"\end{longtable}"])


def main() -> None:
    analyzed, withdrawn = panel()
    lengths = sorted(r["length"] for r in analyzed)
    q1, median, q3 = statistics.quantiles(lengths, n=4, method="inclusive")

    counts: dict[str, int] = {}
    for record in analyzed:
        counts[classify(record["name"])] = counts.get(classify(record["name"]), 0) + 1
    ordered = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))

    pairs = [g for g in (gc(r) for r in analyzed) if g is not None]
    stem_gc = statistics.fmean(s for s, _ in pairs)
    loop_gc = statistics.fmean(l for _, l in pairs)
    enriched = sum(1 for s, l in pairs if s > l)

    breakdown = ", ".join(
        f"{name} ({n})" if name != ordered[-1][0] else f"and {name} ({n})"
        for name, n in ordered)

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(
        "% Generated by scripts/generate_panel_description.py. Do not edit.\n"
        "% Every figure below is computed from data/rfam_families/.\n"
        f"\\newcommand{{\\panelN}}{{{len(analyzed)}}}\n"
        f"\\newcommand{{\\panelCurated}}{{{len(analyzed) + len(withdrawn)}}}\n"
        f"\\newcommand{{\\panelWithdrawn}}{{{len(withdrawn)}}}\n"
        f"\\newcommand{{\\panelClasses}}{{{breakdown}}}\n"
        f"\\newcommand{{\\panelLengthRange}}{{{lengths[0]}--{lengths[-1]}}}\n"
        f"\\newcommand{{\\panelLengthMedian}}{{{median:g}}}\n"
        f"\\newcommand{{\\panelLengthIQR}}{{{q1:g}--{q3:g}}}\n"
        f"\\newcommand{{\\panelStemGC}}{{{stem_gc:.1f}}}\n"
        f"\\newcommand{{\\panelLoopGC}}{{{loop_gc:.1f}}}\n"
        f"\\newcommand{{\\panelGCEnriched}}{{{enriched}}}\n"
        f"\\newcommand{{\\panelGCScored}}{{{len(pairs)}}}\n")

    print(f"panel: {len(analyzed)} analyzed, {len(withdrawn)} withdrawn, "
          f"{len(analyzed) + len(withdrawn)} curated\n")
    print(f"  {'class':<26}{'n':>4}")
    for name, n in ordered:
        print(f"  {name:<26}{n:>4}")
    assert sum(counts.values()) == len(analyzed)
    print(f"  {'':<26}{'---':>4}\n  {'total':<26}{sum(counts.values()):>4}\n")
    print(f"  length   {lengths[0]}-{lengths[-1]} nt, median {median:g}, "
          f"IQR {q1:g}-{q3:g}")
    print(f"  stem GC  {stem_gc:.1f}%   loop GC {loop_gc:.1f}%   "
          f"enrichment {stem_gc - loop_gc:+.1f} points")
    print(f"  stem GC exceeds loop GC in {enriched} of {len(pairs)} families")
    TABLE.write_text(panel_table(analyzed, withdrawn) + "\n")
    print(f"\n  withdrawn: {', '.join(r['name'] for r in withdrawn)}")
    print(f"\n  -> {OUT.relative_to(REPO)}\n  -> {TABLE.relative_to(REPO)}")


if __name__ == "__main__":
    main()
